sudo: false
before_install:
  - pip install --user RangeHTTPServer
  - npm install -g bower
install:
  - cd test
  - bower install
  - cd -
before_script:
  - python -m RangeHTTPServer &
script:
  - phantomjs test/run-jasmine.js http://localhost:8000/test
